### ISSUE TITLE
node v14.21.0. run sisi list-index command

### ISSUE THREAD

**Issue by liu-xi-wang** [frost-beta/sisi#5]
result error:
file:///usr/local/lib/node_modules/@frost-beta/sisi/node_modules/pretty-ms/index.js:49
		valueString ??= String(value);
		            ^^^

SyntaxError: Unexpected token '??='
    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)

**Comment by zcbenz** [comment]
Thanks for reporting this, this tool requires Node >= 22 for running, I'll document the requirement.
